#!/bin/bash
set -ex

ANONCVS=anoncvs@anoncvs.fr.freebsd.org:/home/ncvs

RELENG=RELENG_6_3_0_RELEASE
RPORTS=RELEASE_6_3_0

rm -rf src ports

if test -e src.tar.gz ; then
  tar -xzpf src.tar.gz
  action="update"
else
  action="checkout"
fi

cvs -d $ANONCVS ${action} -r $RPORTS ports/Mk
for i in \
    src/share/mk \
    src/usr.bin/cksum \
    src/usr.bin/file2c \
    src/usr.bin/lex \
    src/usr.bin/make \
    src/usr.bin/mkdep \
    src/usr.bin/yacc \
    src/usr.bin/brandelf \
    src/usr.sbin/btxld \
    src/usr.sbin/config \
    src/usr.sbin/kgzip \
    src/usr.sbin/mtree \
  ; do
  cvs -d $ANONCVS ${action} -r $RELENG $i
  test -e $i
done

rm -f src.tar.gz
tar -czpf src.tar.gz src/ ports/

rm -rf src ports
