#! /bin/sh
# reportbug_cfg - report a bug against a package, asking to update config.sub/config.guess
#
# Copyright (C) 2005 Aurelien Jarno
# Licensed under the GNU GPL v2.

if [ -z "$1" ] ; then
  echo "Usage: $0 sourcepackage"
  exit 1
fi

if [ ! -x "/usr/bin/reportbug" ] ; then
  echo "reportbug not found. Please install if"
  exit 1
fi

BODY="$(mktemp -t reportbug_cfg.XXXXXX)" || exit 1

cat << EOF > $BODY
Hello,


The current version of $1 fails to build on GNU/kFreeBSD, 
because of outdated config.guess and config.sub.

The versions of config.guess and config.sub in $1 are too
old to correctly support Debian GNU/k*BSD.  A version is needed
from year 2005 or later, which is available in the autotools-dev packages
that are in current sarge, etch, and sid.

You can simply copy them manually, but it can also be done 
automatically using the method described in
/usr/share/doc/autotools-dev/README.Debian.gz 

It would also be nice if you cans ask upstream to update 
config.guess and config.sub in their next release.


Thanks for your cooperation.
EOF

/usr/bin/reportbug \
	--no-config-files \
	--no-check-available \
	--no-check-installed \
	--subject="$1(GNU/k*BSD): FTBFS: out of date config.sub/config.guess" \
	--package-version="N/A" \
	--severity=wishlist \
        --body-file=$BODY \
	$1

rm -f $BODY
