#! /bin/sh
# reportbug_cfg - report a bug against a package, asking to update config.sub/config.guess
#
# Copyright (C) 2005 Aurelien Jarno
# Licensed under the GNU GPL v2.

if [ -z "$1" ] ; then
  echo "Usage: $0 sourcepackage"
  exit 1;
fi

PACKAGE=$1
VERSION=$(apt-cache showsrc $PACKAGE | grep ^Version: | head -n 1 | sed -e "s/^Version: //g" -e "s/\+cfg//g")

if [ -z "$VERSION" ] ; then
  echo "Package $PACKAGE not found"
  exit 1;
fi

echo "Reporting bug against $PACKAGE version $VERSION".

if [ -z "$DEBEMAIL" ] ; then
  DEBEMAIL="$USER@$(hostname)"
  echo "Warning: DEBMAIL not set. Using $DEBEMAIL."
fi

if [ -n "$DEBUSER" ] ; then
  MAIL="$DEBEMAIL"
else
  MAIL="$DEBUSER <$DEBEMAIL>"
fi

CHARMAP="$(locale charmap)"
LC_CTYPE="$(locale | grep LC_CTYPE | sed -e "s/LC_CTYPE=\"\(.*\)\"/\1/g")"
LANG="$(locale | grep LANG | sed -e "s/LANG=\(.*\)/\1/g")"

cat << EOF | /usr/sbin/sendmail -bm submit@bugs.debian.org,$DEBEMAIL
From: $MAIL
To: Debian Bug Tracking System <submit@bugs.debian.org>
Subject: ${PACKAGE}_${VERSION}(GNU/k*BSD): FTBFS: out of date config.sub/config.guess
Date: $(date -R)

Package: $PACKAGE
Version: $VERSION
Severity: wishlist

Hello,


The current version of $PACKAGE ($VERSION) fails to build on 
GNU/kFreeBSD, because of outdated config.guess and config.sub.

The versions of config.guess and config.sub in $PACKAGE are too 
old to correctly support Debian GNU/k*BSD.  A version is needed 
from this year, which is available in the autotools-dev packages
that are in current sarge, and sid. 

You can simply copy them manually, but it can also be done 
automatically using the method described in 
/usr/share/doc/autotools-dev/README.Debian.gz

It would also be nice if you cans ask upstream to update 
config.guess and config.sub in their next release.


Thanks for your cooperation.


-- System Information:
Debian Release: $(cat /etc/debian_version)
  APT prefers unstable
  APT policy: (500, 'unstable')
Architecture: $(dpkg-architecture -qDEB_BUILD_ARCH) ($(uname -m))
Kernel: $(uname -s -r)
Locale: LANG=$LANG, LC_CTYPE=$LC_CTYPE (charmap=$CHARMAP)

EOF

echo "Done."		

