#! /bin/sh
# reportbug_libtool - report a bug against a package, asking to update libtool
#
# Copyright (C) 2005 Aurelien Jarno
# Licensed under the GNU GPL v2.

if [ -z "$1" ] ; then
  echo "Usage: $0 sourcepackage"
  exit 1
fi

if [ ! -x "/usr/bin/reportbug" ] ; then
  echo "reportbug not found. Please install if"
  exit 1
fi

BODY="$(mktemp -t reportbug_libtool.XXXXXX)" || exit 1

if apt-cache showsrc $1 | grep -q "^Build-Depends:.*kdelibs.*-dev.*" ; then
  cat << EOF > $BODY
Hello,


The current version of $1 fails to build on
GNU/kFreeBSD, because of outdated libtool.

The version of libtool in $1 is too old to correctly 
support Debian GNU/k*BSD.

Here is how to update the libtool in your package:
  update the admin/ directory from the latest CVS
  make -f admin/Makefile.common

It would also be nice if you can ask upstream to update libtool
in their next release.


Thanks for your cooperation.
EOF
else
  cat << EOF > $BODY
Hello,


The current version of $1 fails to build on
GNU/kFreeBSD, because of outdated libtool.

The version of libtool in $1 is too old to correctly 
support Debian GNU/k*BSD.  libtool 1.5.2-1 or later is need.

Here is how to update the libtool in your package (Make sure you
are using libtool 1.5.2-1 or later:
  libtoolize -c -f
  aclocal (-Im4 might be needed if there's an "m4" template dir)
  autoconf

It would also be nice if you can ask upstream to update libtool 
in their next release.


Thanks for your cooperation.
EOF
fi

/usr/bin/reportbug \
	--no-config-files \
	--no-check-available \
	--no-check-installed \
	--subject="$1(kfreebsd-i386 and kfreebsd-amd64): FTBFS: out of date libtool scripts" \
	--package-version="N/A" \
	--severity=important \
        --body-file=$BODY \
	$1

rm -f $BODY
