#!/bin/bash
set -ex

export CVSROOT=freebsdanoncvs@anoncvs.freebsd.org:/home/ncvs

rm -rf src

if test -e src.tar.gz ; then
  tar -xzpf src.tar.gz
  action="update"
else
  action="checkout"
fi

for i in \
    src/lib/lib{cam,geom,ipx,kvm,sbuf,usbhid} \
    src/lib/lib{stand,z} src/contrib/bzip2 src/lib/libc/i386/{net,string} \
  ; do
  cvs ${action} -r RELENG_5_4_0_RELEASE $i
  test -e $i
done

rm -f src.tar.gz
tar -czpf src.tar.gz src
rm -rf src
