#!/bin/bash
set -ex

ANONCVS=anoncvs@anoncvs.fr.freebsd.org:/home/ncvs
RELENG=RELENG_7_1_0_RELEASE

rm -rf src

if test -e src.tar.gz ; then
  tar -xzpf src.tar.gz
  action="update"
else
  action="checkout"
fi

for i in \
    src/lib/lib{cam,devstat,geom,ipx,kiconv,kvm,sbuf,usbhid} \
  ; do
  cvs -d $ANONCVS ${action} -r $RELENG $i
  test -e $i
done

rm -f src.tar.gz
tar -czpf src.tar.gz src
rm -rf src
