--- a/usr.bin/smbutil/Makefile
+++ b/usr.bin/smbutil/Makefile
@@ -6,6 +6,8 @@
 DPADD=	${LIBSMB} ${LIBKICONV}
 LDADD=	-lsmb -lkiconv
 
+LDADD+=	-L../../lib/libsmb
+
 CONTRIBDIR=	${.CURDIR}/../../contrib/smbfs
 CFLAGS+=	-I${CONTRIBDIR}/include
 
--- a/usr.sbin/mount_smbfs/Makefile
+++ b/usr.sbin/mount_smbfs/Makefile
@@ -8,9 +8,11 @@
 CONTRIBDIR=	${.CURDIR}/../../contrib/smbfs
 CFLAGS+=	-DSMBFS -I${MOUNTDIR} -I${CONTRIBDIR}/include
 
-LDADD=	-lsmb -lkiconv
+LDADD=	-lsmb -lkiconv -ldl
 DPADD=	${LIBSMB} ${LIBKICONV}
 
+LDADD+=	-L../../lib/libsmb
+
 # Needs to be dynamically linked for optional dlopen() access to
 # userland libiconv (see the -E option).
 #
--- a/lib/libsmb/Makefile
+++ b/lib/libsmb/Makefile
@@ -6,7 +6,7 @@
 LIB=	smb
 SHLIB_MAJOR=	4
 DPADD=	${LIBKICONV}
-LDADD=	-lkiconv
+LDADD=	-lkiconv -ldl
 
 SRCS=	rcfile.c ctx.c cfopt.c subr.c nls.c rap.c mbuf.c rq.c file.c \
 	print.c \
