#!/bin/bash
set -e

SUPPORTED_LOCALES="__SUPPORTED_LOCALES__"

. /usr/share/debconf/confmodule
db_version 2.0

if test -f /etc/locale.gen; then
  LG=/etc/locale.gen
  SELECTED_LOCALES=$(egrep -v "^#|^$" $LG | tr "\n" "," | sed -e "s/,/, /g" -e "s/, *$//")
  db_set locales/locales_to_be_generated "${SELECTED_LOCALES}"
else
  LG=/dev/null
fi

SUPPORTED_LOCALES=$( (cat $LG && echo "$SUPPORTED_LOCALES") | egrep -hv "^#|^$" | sort -u | tr "\n" "," | sed -e "s/,/, /g" -e "s/, *$//")

db_subst locales/locales_to_be_generated locales "${SUPPORTED_LOCALES}"
db_capb multiselect
db_input medium locales/locales_to_be_generated || true
db_go

db_get locales/locales_to_be_generated && DEFAULT_LOCALES=$(echo $RET | sed -e 's/Leave alone,*//g' -e 's/ [^ ]*,/,/g' -e 's/ [^ ]*$//')

if test -z "$DEFAULT_LOCALES"; then
    DEFAULT_LOCALES=C
else
    DEFAULT_LOCALES="C, $DEFAULT_LOCALES"
fi
db_subst locales/default_environment_locale locales $DEFAULT_LOCALES
db_input medium locales/default_environment_locale || true
db_go
