#! /bin/sh
set -e

LG="/etc/locale.gen"

if [ "$1" = configure ]; then

    . /usr/share/debconf/confmodule
    db_version 2.0

    if test ! -e $LG || grep -q "XXX GENERATED XXX" $LG || dpkg --compare-versions "$2" le 2.2.4-7; then
	db_get locales/locales_to_be_generated && SELECTED_LOCALES=$RET
	echo $SELECTED_LOCALES | grep -q "Leave alone" && LEAVE_FLAG="yes"
	if test -z $LEAVE_FLAG; then
	    cat > $LG << EOF
# This file lists locales that you wish to have built. You can find a list
# of valid supported locales at /usr/share/i18n/SUPPORTED. Other
# combinations are possible, but may not be well tested. If you change
# this file, you need to rerun locale-gen.
#
# XXX GENERATED XXX
#
# NOTE!!! If you change this file by hand, and want to continue
# maintaining manually, remove the above line. Otherwise, use the command
# "dpkg-reconfigure locales" to manipulate this file. You can manually
# change this file without affecting the use of debconf, however, since it
# does read in your changes.

EOF
	    echo $SELECTED_LOCALES | sed -e 's/, /,/g' | tr ',' '\n' >> $LG
	fi
    fi

    # Update requested locales
    if test -z $LEAVE_FLAG; then
	/usr/sbin/locale-gen
    fi

    # Set default LANG environment var
    db_get locales/default_environment_locale && SELECTED="$RET"
    if [ -n "$SELECTED" -a "$SELECTED" != "Leave alone" ]; then
	umask 022
	grep -v '^LANG=' /etc/environment > /etc/environment.tmp 2> /dev/null || true
	test "$SELECTED" = "None" || echo "LANG=$SELECTED" >> /etc/environment.tmp
	cat /etc/environment.tmp > /etc/environment
	rm -f /etc/environment.tmp
    fi
fi
