#!/bin/bash
set -ex

rm -rf src

if test -e src.tar.bz2 ; then
  tar -xjpf src.tar.bz2
  action="update"
else
  action="checkout"
fi

for i in src/{sys,usr.sbin/config} ; do
  cvs -d freebsdanoncvs@anoncvs.freebsd.org:/home/ncvs ${action} -r RELENG_6_0_0_RELEASE $i
done

grep ^src/ debian/copyright | xargs rm -rf

tar -cjpf src.tar.bz2 src/

rm -rf src
