#!/bin/sh
srcsysdir=/usr/src/sys
rm -rf orig/*
# Take all include files which occur in /usr/include.
for f in `
  cd $srcsysdir
  for f in \`find . -name '*.h'\`; do
    if test -d /usr/include/\`echo $f | sed -e 's,^\./,,' -e 's,/.*,,'\`; then
      echo $f
    fi
  done \
  | sed -e 's,^\./,,'
`; do
  echo "Copying $f"
  mkdir -p `echo orig/$f | sed -e 's,/[^/]*$,,'`
  cp -p $srcsysdir/$f orig/$f
done
# Also take the CPU dependent include files.
for f in `
  cd $srcsysdir
  for cputypes in */include/types.h; do
    cpu=\`echo $cputypes | sed -e 's,/include/types.h,,'\`
    find $cpu/include -name '*.h'
  done
`; do
  g=`echo $f | sed -e 's,/include/,/machine/,'`
  echo "Copying $g"
  mkdir -p `echo orig/$g | sed -e 's,/[^/]*$,,'`
  cp -p $srcsysdir/$f orig/$g
done
