#!/bin/sh
(for i in `cd /boot/kernel/ && ls *.ko | sed -e "s/\.ko$//g"` ; do
  echo -n "$i: "
  grep "^${i}_load=\"NO\".*#" /boot/defaults/loader.conf | sed -e "s/[^#]*# //g"
  echo
done) | grep -v "^$"
