#!/bin/sh -e

if [ "$1" = "configure" ]
then
    ldconfig

    package=`basename $0 .postinst`
    opt=`echo $package | sed 's/.*-//'`

    if [ -f /etc/ld.so.nohwcap ]; then
        grep -v $opt /etc/ld.so.nohwcap > /etc/ld.so.nohwcap.tmp
        mv /etc/ld.so.nohwcap.tmp /etc/ld.so.nohwcap
        test -s /etc/ld.so.nohwcap || rm -f /etc/ld.so.nohwcap
    fi
fi
