#!/bin/bash
set -ex

ANONCVS=anoncvs@anoncvs.fr.freebsd.org:/home/ncvs
RELENG=RELENG_6_3_0_RELEASE

rm -rf src

if test -e src.tar.gz ; then
  tar -xzpf src.tar.gz
  action="update"
else
  action="checkout"
fi

for i in \
    src/sbin/dmesg src/sbin/swapon src/sbin/sysctl \
    src/sbin/ifconfig src/sbin/route src/usr.bin/netstat \
    src/sbin/kldconfig src/sbin/kldload src/sbin/kldstat src/sbin/kldunload \
    src/sbin/mount_std src/sbin/umount src/usr.sbin/rpc.umntall \
    src/sbin/mount_{cd9660,ext2fs,hpfs,msdosfs,nfs,nfs4,ntfs,nullfs,udf,umapfs,unionfs} \
    src/sbin/mount{,_autofs,_reiserfs} \
    src/usr.bin/{ktrace,kdump} src/usr.sbin/jail src/usr.sbin/ppp{,ctl,d} \
    src/sbin/{mdconfig,ccdconfig,ipfw} \
    src/{contrib/pf,sbin/pfctl,usr.sbin/authpf} \
    src/usr.sbin/kbdcontrol src/share/syscons/keymaps \
    src/bin/chflags \
  ; do
  cvs -d $ANONCVS ${action} -r $RELENG $i
  test -e $i
done

rm -f src.tar.gz
tar -czpf src.tar.gz src
rm -rf src
