#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_input medium kfreebsd-config/network || true
db_go

db_input high kfreebsd-config/sound || true
db_go

db_input high kfreebsd-config/other || true
db_go
