# This file is automatically generated. Do not edit.
PATCHES=$(subst debian/ap/,,$(shell echo $(wildcard debian/ap/*.ap)))
rebuild-patches: 
	cd build-tree; \
	for i in $(PATCHES); do \
		p=$${i/.ap/.diff}; \
		../debian/mk/autopatch ../debian/ap/$$i >../debian/patches/$$p; \
		patch -p0 -f --no-backup-if-mismatch <../debian/patches/$$p; \
	done
