#!/bin/sh
set -e

args=""
verbose=false
while [ $# -gt 0 ]; do
  case "$1" in
    -v) verbose=true ;;
    *)  if [ -n "${args}" ] ; then args="${args} $1" ; else args="$1" ; fi ;;
  esac
  shift
done

if ! ${verbose} ; then
  exec >/dev/null
fi

exec -a swapoff swapoff.real ${args}
