#!/bin/sh
set -e

args=""
dirs=""
remount_readonly=false

while [ $# -gt 0 ]; do
  case "$1" in
    -d|-l) ;;
    -r) remount_readonly=true ;;
    -*)  if [ -n "${args}" ] ; then args="${args} $1" ; else args="$1" ; fi ;;
    *) dirs="${dirs} $1" ;;
  esac
  shift
done

for i in ${dirs} ; do
  if ! /lib/freebsd/umount ${args} ${i} && ${remount_readonly} ; then
    /lib/freebsd/mount -o ro ${i}
  fi
done
