#!/bin/sh
rm -rf import
for f in `
  cd orig
  find . -type f -name '*.h' | sed -e 's,^\./,,'
`; do
  case $f in
    alpha/machine/pal.h | \
    netinet/icmp6.h | \
    netinet/in.h | \
    netinet/ip6.h | \
    netinet/ip_icmp.h | \
    netinet/tcp.h | \
    netinet/udp.h | \
    sys/cdefs.h | \
    sys/dir.h | \
    sys/fcntl.h | \
    sys/file.h | \
    sys/gmon.h | \
    sys/ioctl.h | \
    sys/ipc.h | \
    sys/ktrace.h | \
    sys/mman.h | \
    sys/mount.h | \
    sys/msg.h | \
    sys/mtio.h | \
    sys/poll.h | \
    sys/ptrace.h | \
    sys/resource.h | \
    sys/select.h | \
    sys/sem.h | \
    sys/shm.h | \
    sys/signal.h | \
    sys/socket.h | \
    sys/socketvar.h | \
    sys/stat.h | \
    sys/syslog.h | \
    sys/syscall.h | \
    sys/termios.h | \
    sys/time.h | \
    sys/timeb.h | \
    sys/times.h | \
    sys/ttychars.h | \
    sys/ttydefaults.h | \
    sys/types.h | \
    sys/ucontext.h | \
    sys/uio.h | \
    sys/un.h | \
    sys/unistd.h | \
    sys/utsname.h | \
    sys/wait.h )
      ;;
    *)
      case $f in
        sys/errno.h) g=bits/errno.h ;;
        *) g=$f ;;
      esac
      echo "Creating import/$g"
      mkdir -p `echo import/$g | sed -e 's,/[^/]*$,,'`
      sed \
          -e 's/\([^a-z_]\)\(time_t\|timeval\|timespec\|itimerval\)\([^a-z_]\)/\1__kernel_\2\3/g' \
          -e 's/^\(time_t\|timeval\|timespec\|itimerval\)\([^a-z_]\)/__kernel_\1\2/' \
          -e 's/\([^a-z_]\)\(time_t\|timeval\|timespec\|itimerval\)$/\1__kernel_\2/' \
          < orig/$f > import/$g
      if test -f patches/$f.diff; then
        patch import/$g < patches/$f.diff
      fi
      ;;
  esac
done
