--- a/cddl/lib/libuutil/Makefile
+++ b/cddl/lib/libuutil/Makefile
@@ -15,6 +15,8 @@
 	uu_pname.c \
 	uu_strtoint.c
 
+LDADD= -lpthread -lrt -lbsd
+
 WARNS?=	0
 CFLAGS+= -DNATIVE_BUILD
 CFLAGS+= -I${.CURDIR}/../../../cddl/contrib/opensolaris/lib/libuutil/common
--- a/cddl/lib/libzfs/Makefile
+++ b/cddl/lib/libzfs/Makefile
@@ -7,7 +7,12 @@
 
 LIB=	zfs
 DPADD=	${LIBMD} ${LIBPTHREAD} ${LIBUMEM} ${LIBUTIL}
-LDADD=	-lmd -lpthread -lumem -lutil -lnvpair -luutil -lgeom -lm
+LDADD=	-lmd -lpthread -lumem -lnvpair -luutil -lgeom -lm -lbsd
+
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= ${.CURDIR}/../../../cddl/lib/libavl/libavl.a
 
 SRCS=	deviceid.c \
 	fsshare.c \
--- a/cddl/lib/libzpool/Makefile
+++ b/cddl/lib/libzpool/Makefile
@@ -57,7 +57,11 @@
 CFLAGS+=	-I${.CURDIR}/../../../lib/libthr/arch/${MACHINE_CPUARCH}/include
 
 DPADD=		${LIBMD} ${LIBPTHREAD} ${LIBZ}
-LDADD=		-lmd -lpthread -lz -lumem -lnvpair -lavl
+LDADD=		-lmd -lpthread -lz -lumem -lnvpair -lbsd -lrt
+
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= ${.CURDIR}/../../../cddl/lib/libavl/libavl.a
 
 # atomic.S doesn't like profiling.
 NO_PROFILE=
--- a/cddl/sbin/zfs/Makefile
+++ b/cddl/sbin/zfs/Makefile
@@ -23,6 +23,12 @@
 
 DPADD=	${LIBBSDXML} ${LIBGEOM} ${LIBM} ${LIBNVPAIR} ${LIBSBUF} ${LIBUMEM} \
 	${LIBUTIL} ${LIBUUTIL} ${LIBZFS}
-LDADD=	-lgeom -lnvpair -lumem -lutil -luutil -lzfs
+LDADD=	-lgeom -lnvpair -lumem -luutil -lzfs -lbsd
+
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libzfs
+
 
 .include <bsd.prog.mk>
--- a/cddl/sbin/zpool/Makefile
+++ b/cddl/sbin/zpool/Makefile
@@ -28,6 +28,12 @@
 
 DPADD=	${LIBAVL} ${LIBBSDXML} ${LIBGEOM} ${LIBM} ${LIBNVPAIR} ${LIBSBUF} \
 	${LIBUMEM} ${LIBUTIL} ${LIBUUTIL} ${LIBZFS}
-LDADD=	-lavl -lgeom -lnvpair -lumem -lutil -luutil -lzfs
+LDADD=	-lgeom -lnvpair -lumem -luutil -lzfs -lbsd
+
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+=	-L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+=	${.CURDIR}/../../../cddl/lib/libavl/libavl.a
 
 .include <bsd.prog.mk>
--- a/cddl/usr.bin/zinject/Makefile
+++ b/cddl/usr.bin/zinject/Makefile
@@ -23,4 +23,11 @@
 	${LIBZFS} ${LIBZPOOL}
 LDADD=	      -lgeom -lm -lnvpair -lumem -luutil -lzfs -lzpool
 
+LDADD+= -lbsd
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzpool
+
 .include <bsd.prog.mk>
--- a/cddl/usr.bin/ztest/Makefile
+++ b/cddl/usr.bin/ztest/Makefile
@@ -19,7 +19,12 @@
 
 DPADD=	${LIBM} ${LIBNVPAIR} ${LIBUMEM} ${LIBZPOOL} \
 	${LIBPTHREAD} ${LIBZ} ${LIBAVL}
-LDADD=	-lm -lnvpair -lumem -lzpool -lpthread -lavl
+LDADD=	-lm -lnvpair -lumem -lzpool -lpthread -lbsd -ldl -lrt
+
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzpool
+LDADD+= ${.CURDIR}/../../../cddl/lib/libavl/libavl.a
 
 CSTD=	c99
 
--- a/cddl/usr.sbin/zdb/Makefile
+++ b/cddl/usr.sbin/zdb/Makefile
@@ -27,5 +27,11 @@
 	${LIBUUTIL} ${LIBZ} ${LIBZFS} ${LIBZPOOL}
 LDADD=	-lgeom -lm -lnvpair -lpthread -lumem -luutil -lzfs -lzpool
 
+LDADD+= -lbsd
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzpool
 
 .include <bsd.prog.mk>
