#! /bin/sh
### BEGIN INIT INFO
# Provides:          moused freebsd-moused
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: moused sysv init script
# Description:       Start the console mouse daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/moused
NAME=moused
DESC="FreeBSD mouse daemon"

test -x $DAEMON || exit 0

if [ -f /etc/moused.conf ] ; then
	. /etc/moused.conf
fi

if test -z "${mouse_device}" ; then
  echo WARNING: mouse device unconfigured.
else
  DAEMON_OPTS="$DAEMON_OPTS -p ${mouse_device}"
fi
if test -n "${mouse_type}" ; then
  DAEMON_OPTS="$DAEMON_OPTS -t ${mouse_type}"
fi

set -e

case "$1" in
  start)
	if test -z "${mouse_device}" ; then exit 1 ; fi
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON
	echo "$NAME."
	;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	if test -z "${mouse_device}" ; then exit 1 ; fi
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
