#!/bin/sh -ex
#
# $Id$
#

# extract mfsroot
mdconfig -a -t vnode -f boot.flp -u md0
mount /dev/md0 /mnt
gunzip -c /mnt/mfsroot.gz > ./mfsroot
umount /mnt
mdconfig -d -u md0

# insert init into mfsroot
mdconfig -a -t vnode -f mfsroot -u md0
mount /dev/md0 /mnt
rm -f /mnt/stand/sysinstall
install -m755 init /mnt/stand/sysinstall
umount /mnt
mdconfig -d -u md0

# insert mfsroot
mdconfig -a -t vnode -f boot.flp -u md0
mount /dev/md0 /mnt
gzip -c9 ./mfsroot > /mnt/mfsroot.gz
umount /mnt
mdconfig -d -u md0

# cleanup
rm -f mfsroot

