#!/bin/sh
set -e

if [ "$1" = configure ]; then
    install-info --quiet --section '^GNU Libraries:' 'GNU Libraries:' \
    /usr/share/info/libc.info.gz

    if command -v install-docs >/dev/null 2>&1; then
	echo -n "Registering GNU C Library Documentation..."
	install-docs -i /usr/share/doc-base/glibc-manual >/dev/null 2>&1
	echo "done."
    fi
fi
