#!/bin/sh
set -e

if [ "$1" = remove ]; then
    install-info --quiet --remove libc

    install-info --quiet --remove /usr/share/doc/glibc-doc/libc.info.gz

    if command -v install-docs >/dev/null 2>&1; then
	install-docs -r glibc-manual >/dev/null 2>&1
    fi
fi
