=head1 NAME

catchsegv - Catch segmentation faults in programs

=head1 SYNOPSIS

B<catchsegv> B<program> [B<args>]

=head1 DESCRIPTION

Used to debug segmentation faults in programs. The output is the
content of registers, plus a backtrace. Basically you call your
program and its arguments as the arguments to catchsegv.

=head1 AUTHOR

I<catchsegv> was written by Ulrich Drepper for the GNU C Library

This man page was written by Ben Collins E<lt>bcollins@debian.orgE<gt> for
the Debian GNU/Linux system.
