=head1 NAME

getconf - Query system configuration variables

=head1 SYNOPSIS

B<getconf> [B<-v specification>] system_var

B<getconf> [B<-v specification>] path_var pathname

=head1 DESCRIPTION

B<-v>

	Indicate the specification and version for which to obtain
	configuration variables.

B<system_var>

	A system configuration variable, as defined by sysconf(3) or
	confstr(3).

B<path_var>

	A system configuration variable as defined by pathconf(3). This
	must be used with a pathname.

=head1 AUTHOR

I<getconf> was written by Roland McGrath for the GNU C Library

This man page was written by Ben Collins E<lt>bcollins@debian.orgE<gt> for
the Debian GNU/Linux system.

=head1 SEE ALSO

B<sysconf>(3), B<pathconf>(3), B<confstr>(3)
