=head1 NAME

getent - get entries from administrative database

=head1 SYNOPSIS

B<getent> I<database> [I<key> ...]

=head1 DESCRIPTION

The I<getent> program gathers entries from the specified
administrative database using the specified search keys.
Where I<database> is one of passwd, group, hosts, services, protocols,
or networks.

=head1 AUTHOR

I<getent> was written by Thorsten Kukuk for the GNU C Library.

This man page was written by Joel Klecker E<lt>espy@debian.orgE<gt> for
the Debian GNU/Linux system.
