=head1 NAME

iconv - Convert encoding of given files from one encoding to another

=cut

=head1 SYNOPSIS

iconv B<-f> I<encoding> B<-t> I<encoding> I<inputfile>

=head1 DESCRIPTION

The B<iconv> program converts the encoding of characters in
I<inputfile> from one coded character set to another. The result is
written to standard output unless otherwise specified by the
B<--output> option.

B<--from-code>, B<-f> I<encoding>

Convert characters from I<encoding>

B<--to-code>, B<-t> I<encoding>

Convert characters to I<encoding>

B<--list>

List known coded character sets

B<--output>, B<-o> I<file>

Specify output file (instead of stdin)

B<--verbose>

Print progress information.

=head1 AUTHOR

I<iconv> was written by Ulrich Drepper as part of the GNU C Library.

This man page was written by Joel Klecker E<lt>espy@debian.orgE<gt>,
for the Debian GNU/Linux system.


