=head1 NAME

sprof - Read and display shared object profiling data

=head1 SYNOPSIS

B<sprof> B<-p>|B<-c> [B<-q>]

=head1 DESCRIPTION

B<--call-pairs>, B<-c>

	print list of count paths and their number of use

B<--flat-profile>, B<-p>

	generate flat profile with counts and ticks

B<--graph>, B<-q>

	generate call graph

=head1 AUTHOR

I<sprof> was written by Ulrich Drepper for the GNU C Library

This man page was written by Joel Klecker E<lt>espy@debian.orgE<gt> for
the Debian GNU/Linux system.
