sbin/geom/core/geom				/sbin

sbin/geom/class/cache/geom_cache.so		/lib/geom
sbin/geom/class/concat/geom_concat.so		/lib/geom
sbin/geom/class/eli/geom_eli.so			/lib/geom
sbin/geom/class/label/geom_label.so		/lib/geom
sbin/geom/class/mirror/geom_mirror.so		/lib/geom
sbin/geom/class/nop/geom_nop.so			/lib/geom
sbin/geom/class/raid3/geom_raid3.so		/lib/geom
sbin/geom/class/sched/geom_sched.so		/lib/geom
sbin/geom/class/shsec/geom_shsec.so		/lib/geom
sbin/geom/class/stripe/geom_stripe.so		/lib/geom
