build-tree/src/sbin/mount/mount		/lib/freebsd
build-tree/src/sbin/umount/umount	/lib/freebsd
build-tree/src/sbin/sysctl/sysctl	/lib/freebsd

scripts/bin/mount			/bin
scripts/bin/sysctl			/bin
scripts/sbin/umount			/sbin

build-tree/src/sbin/dmesg/dmesg				/bin
build-tree/src/sbin/swapon/swapon			/sbin
build-tree/src/sbin/mdconfig/mdconfig			/sbin
build-tree/src/sbin/mount_std/mount_std			/sbin
build-tree/src/sbin/mount_autofs/mount_autofs		/sbin
build-tree/src/sbin/mount_cd9660/mount_cd9660		/sbin
build-tree/src/sbin/mount_ext2fs/mount_ext2fs		/sbin
build-tree/src/sbin/mount_hpfs/mount_hpfs		/sbin
build-tree/src/sbin/mount_msdosfs/mount_msdosfs		/sbin
build-tree/src/sbin/mount_ntfs/mount_ntfs		/sbin
build-tree/src/sbin/mount_nullfs/mount_nullfs		/sbin
build-tree/src/sbin/mount_reiserfs/mount_reiserfs	/sbin
build-tree/src/sbin/mount_udf/mount_udf			/sbin
build-tree/src/sbin/mount_umapfs/mount_umapfs		/sbin
build-tree/src/sbin/mount_unionfs/mount_unionfs		/sbin
